export const alertActions = {

  SHOW_ALERT: 'SHOW_ALERT',

};

export const dataActions = {

  PROCESS_FILE: 'PROCESS_FILE',
  INCOMING_DATA: 'INCOMING_DATA',
  PREVIOUS_TRACE: 'PREVIOUS_TRACE',
  NEXT_TRACE: 'NEXT_TRACE',
  SET_FOCUS_RANGE: 'SET_FOCUS_RANGE',

};